export const ADD_CART="ADD_CART";
export const REMOVE_CART="REMOVE_CART";
export const INCREMENT_COUNT="INCREMENT_COUNT";
export const DECREMENT_COUNT="DECREMENT_COUNT";
export const CLEAR_CART="CLEAR_CART";
